### ISSUE TITLE
missing data folder

### ISSUE THREAD

**Issue by capybaralet** [neocxi/pixelsnail-public#1]
The pixelCNN++ code [here](https://github.com/openai/pixel-cnn) has a "data" folder that this code also seems to rely on (I just copied it from that repo and it seemed to work).  That code has imageio as an additional dependency.

**Comment by capybaralet** [comment]
Actually I'm not sure if that code works OOB here.
It would be nice to know what to use for `data.cifar10_data` (in train.py).

I have queue-related errors using that code (near the end of the first epoch). 
I attached stderr/stdout.
[stdout.txt](https://github.com/neocxi/pixelsnail-public/files/1650331/stdout.txt)
[stderr.txt](https://github.com/neocxi/pixelsnail-public/files/1650332/stderr.txt)

**Comment by capybaralet** [comment]
(my fork/branch, in case it's useful):
https://github.com/capybaralet/pixelsnail-public/tree/dk

**Comment by neocxi** [comment]
should be fixed in https://github.com/neocxi/pixelsnail-public/commit/0d0c01a0eedfe642b3ffdb137ce948e8340e95f7
